In [1]:
import numpy as np
import pandas as pd

#### OneHotEncoder
> Encode categorical features as a one-hot numeric array.


In [2]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
X = np.array(["Male", "Female", "Female", "Male", "Female"])

In [5]:
enc = OneHotEncoder(handle_unknown='ignore')

In [8]:
enc.fit(X.reshape(1, -1))

OneHotEncoder(handle_unknown='ignore')

In [10]:
enc.categories_

[array(['Male'], dtype='<U6'),
 array(['Female'], dtype='<U6'),
 array(['Female'], dtype='<U6'),
 array(['Male'], dtype='<U6'),
 array(['Female'], dtype='<U6')]

In [13]:
enc.transform(np.array(["Male", "Female", "Male", "Female", "Female"]).reshape(1, -1)).toarray()

array([[1., 1., 0., 0., 1.]])

#### Docs Example

In [14]:
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [16]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

### LabelEncoder
* Encode target labels with value between 0 and n_classes-1.

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
enc = LabelEncoder()

In [20]:
X = np.array(["Male", "Female", "Female", "Male", "Female"])
enc.fit(X)

LabelEncoder()

In [21]:
enc.classes_

array(['Female', 'Male'], dtype='<U6')

In [27]:
enc.transform(["Female", "Male", "Male", "Female"])

array([0, 1, 1, 0])