## Regression Problem on Stars DataSet
> We want to predict the tempreature based on `L` and `R`

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import pandas as pd

In [2]:
stars = pd.read_csv('Stars.csv')
stars.head()

Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

In [15]:
y = stars.Temperature.values
X =  stars[:].values[:, 1:3]
y.shape, X.shape

((240,), (240, 2))

### Data Spliting

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33, test_size=.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((192, 2), (192,), (48, 2), (48,))

In [38]:
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [39]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled[:2], X_test_scaled[:2]

(array([[-0.57819376, -0.4329358 ],
        [-0.57819374, -0.43247123]]),
 array([[-0.57819378, -0.4328996 ],
        [-0.57819377, -0.43339412]]))

### Comparing different Models

In [62]:
clf = KNeighborsRegressor()
clf.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [63]:
clf.score(X_train_scaled, y_train)

0.5673032142577725

In [64]:
clf.score(X_test_scaled, y_test)

0.36812523048935575

In [65]:
clf.predict(list(X_test_scaled[:2])), y_test[:2]

(array([ 3172.2, 14108. ]), array([ 3142, 16790], dtype=int64))

> This is the worst model. **This is usually caused by working with unrelated data.** The better model to predict this was found to be `KNeighborsRegressor()`